### ISSUE TITLE
SASL EXTERNAL support

### ISSUE THREAD

**Issue by Ascrod** [Ascrod/ambassador#24]
Once we get SASL 3.1 working with `AUTHENTICATE PLAIN`, I'd like to see if we can also implement `AUTHENTICATE EXTERNAL`. Choosing between plain and external authentication would need to be a per-server configuration. Although the [SASL spec](https://tools.ietf.org/html/rfc4422#appendix-A) indicates that the client cannot assume the form of credentials used, it appears that the de factor standard for IRCv3 is a client certificate, which we can store in the Cert Manager.

Depends on #3.

**Comment by Ascrod** [comment]
I've been testing with this, and I have found that identification with certificates already works without any additional code. Here are the steps I have been using:
1) Add a personal certificate to the Certificate Manager.
2) Connect to a server or network that supports identification with certificates (freenode, espernet, OFTC, moznet, rizon).
3) At the "User Identification Request" prompt, choose the loaded certificate and click "OK". (Note: the "Remember this decision" option does not seem to persist across restarts of the host/stand-alone application, and is apparently a [longstanding bug](https://bugzilla.mozilla.org/show_bug.cgi?id=634697).)
4) Once connected, verify that the fingerprint was accepted. Methods for this vary. Sometimes the server sends a NOTICE prior to the welcome message containing the fingerprint. You can also see it in a 276 response to WHOIS.
5) Add the fingerprint to your services account, e.g. "msg Nickserv CERT ADD".

I suppose this counts as SASL EXTERNAL with certificates, so closing this issue. I may do a write-up on the wiki later about how to use personal certificates with Ambassador.

**Comment by kn-yami** [comment]
> Note: the "Remember this decision" option does not seem to persist across restarts of the host/stand-alone application, and is apparently a longstanding bug.

After using the cert-based SALS auth for a few months I can say that the "Remember this decision" option will usually refuse to work even within the same session.
