### ISSUE TITLE
Update docs (typo)

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#25]
> The input area can be switched to multiline mode by pressing [CTRL]+[UP]. Press [CTRL]+[ENTER] to sent the text to the server. In multiline mode, the text you type not scanned for commands, so stray / characters will not affect your post. To return to single line mode, press [CRTL]+[DOWN].

See the last few words: CRTL instead of CTRL. If I had editing rights on the wiki I would have changed it myself.

**Comment by Ascrod** [comment]
Good catch. That was actually copied over from the original DYK file.

Fixed now. Thanks for pointing it out.
