### ISSUE TITLE
Notification title is ChatZilla on Linux, other branding issues

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#26]
Hi. 

I faced an issue on Linux where the notification title was "ChatZilla", but there are probably other references to ChatZilla remaining. Just check out the references to ChatZilla that are remaining:
https://github.com/Ascrod/ambassador/search?q=chatzilla&unscoped_q=chatzilla

**Comment by Ascrod** [comment]
This has already been fixed in 8a9ad1f35c35f6933227dadb56245aa234711bba. The rest of the references are either comments, unused code, or legitimate (links to FAQ and motifs page), which I may clean up eventually but currently they are not a high priority.
