### ISSUE TITLE
Add a screenshot of Ambassador to the README

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#28]
Would you consider that?

**Comment by Smile4ever** [comment]
For your convenience:
![ambassador](https://user-images.githubusercontent.com/544411/45711379-afd9cb80-bb89-11e8-9b14-a8b8d3384eca.png)

**Comment by Ascrod** [comment]
I want to keep the README as a brief introduction. I did include a screenshot on the [add-ons site](https://addons.palemoon.org/addon/ambassador/) (which I need to update) and I may also include one on the wiki (which I also need to update) at some point. Thank you for the suggestion though.
