### ISSUE TITLE
Update URL should be....

### ISSUE THREAD

**Issue by NazcaLine** [Ascrod/ambassador#29]
https://github.com/Ascrod/ambassador/releases/latest/

.... in order to receive latest update.

**Comment by Smile4ever** [comment]
Or does he mean app.releaseNotesURL? For me, currently, it is http://www.github.com/ascrod/ambassador/releases/ Maybe app.releaseNotesURL should default to HTTPS?

**Comment by Ascrod** [comment]
I've updated the URL in several places to use the `latest` folder and https. Commit coming soon.

**Comment by Ascrod** [comment]
Fixed with 09bb9c57ac5f01358f6ec9f0ebb74f7ad37eeff7.
