### ISSUE TITLE
How should I provide the Dutch locale?

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#31]
Please provide me instructions on how to translate Ambassador in Dutch. I know I can make some properties files, but I would like to know exactly what is required.

**Comment by Ascrod** [comment]
You'll have to do it by hand until I can get the build system properly patched. The translated content is relatively easy: simply copy and translate the files within locales/en-US. You will also need the install.rdf template in locales/generic - just replace all the preprocessor variables with actual values. These should be the only Ambassador-specific parts required.

The rest is pretty standard add-on construction. If you need further general help on making a language pack, please use the forum. Discussions there are more visible to UXP contributors, and they may be able to give you some more general guidance on how to make language packs for UXP applications than I can. There should also be some documentation on MDN that may be helpful as well.

**Comment by Smile4ever** [comment]
Since you opened #36 I'm going to close this. I submitted a pull request for the Dutch locale.
