### ISSUE TITLE
Typo in tooltip (preferences)

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#35]
![image](https://user-images.githubusercontent.com/544411/45781689-fc440a80-bc60-11e8-99d3-229ca87eaf5f.png)

supressed => suppressed

**Comment by Ascrod** [comment]
Looks like that came from the original code. Good catch. I'll push the commit for this soon.

**Comment by Ascrod** [comment]
Fixed with 2d607e4016861aadfdec3f933fe106f9587a3222.
