### ISSUE TITLE
nsisstrings.properties browser

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#41]
INTRO_BLURB1=***, the browser that chooses you above everything else.
INSTALL_BLURB1=You're about to enjoy the very latest in speed, flexibility and security so you're always in control.
INSTALL_BLURB2=That's because $BrandShortName is made by a non-profit to make browsing and the Web better for you.
INSTALL_BLURB3=You're also joining a global community of users, contributors and developers working to make the best browser in the world.

This is not a browser, is it? How do I translate it, if at all?

**Comment by Ascrod** [comment]
These strings are leftover remnants from the Firefox stub installer, which doesn't exist in the UXP tree and definitely doesn't apply here. I'll submit a commit to remove these soon.
