### ISSUE TITLE
Clean out legacy - remove warning / error for bug 318419

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#42]
This bug is so old, that it probably doesn't matter anymore. As such, it does not belong in a modern codebase like Ambassador.

The reference that I found is in ambassador.properties.

https://bugzilla.mozilla.org/show_bug.cgi?id=318419

**Comment by Ascrod** [comment]
Yeah, looks like that bug was fixed over a decade ago. The workaround code in handlers.js and the associated strings can be removed.
