### ISSUE TITLE
List of shortcuts for the wiki

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#44]
## Shortcuts

This page contains an overview of the available shortcuts in Ambassador.

# General
* Control+A - Select all
* Control+X - Cut
* Control+C - Copy
* Control+F - Find text in current view.
* Control+G - Find again
* Control+Plus/Control+Equal - Make text bigger
* Control+Minus - Make text smaller
* Control+P - Print
* Control+S - Save

# Input box
* Escape - Focus the input box.
* F6/Shift+F6 - Cycle focus through the input box, chat area and userlist.
* Up/Down - Scroll through recent inputs.

# Chat area
* Control+L - Clear view
* Page Up/Page Down - Scroll the chat area by about one screen.
* Control+Shift+X - Switch the text direction between left-to-right and right-to-left. 

# Tab and window management
* Control+Tab/Control+Page Down - Switch to the next/previous tab.
* Control+Shift+Tab/Control+Page Up - Switch to the next/previous tab.
* Control+1...Control+8 - Switch to tab 1 through 8.
* Control+9 - Switch to the last tab.
* Control+W - Close current tab

# IRC actions
* Control+J - Join a channel.
* Control+D - Disconnect from all networks.

# Layout
* Control+Shift+L - Hide/show user list
* Control+Shift+T - Hide/show tab strip
* Control+Shift+S - Hide/show status bar
* Control+Shift+H - Hide/show header bar

# Tools
* Control+Shift+A - Addons
* Control+Shift+J - JavaScript Console

**Comment by Ascrod** [comment]
I really don't think it is that useful to have a whole page for shortcuts. Most of these are already visible from the menus, and the rest are listed in the existing ChatZilla FAQ which is linked to in the help section. I think only the more obscure shortcuts would belong on a wiki page, and I'm not sure if one is quite necessary just yet.
