### ISSUE TITLE
Add support for IceDove

### ISSUE THREAD

**Issue by Ascrod** [Ascrod/ambassador#74]
Hyperbola has requested support for IceDove. Since it's a rebranded build of Interlink, this shouldn't be too difficult.

**Comment by g4jc** [comment]
Thanks for offering to support it.

All that should be needed is this, but the links aren't working in Interlink/ID at the moment as discussed. Attached patch.
[ID_GUID.txt](https://github.com/Ascrod/ambassador/files/4536589/ID_GUID.txt)

**Comment by g4jc** [comment]
May also be nice to include the ability to embed inside tabs in IL/ID.

Patch borrowed from Interlink's Error Console pref:
 [tab.txt](https://github.com/Ascrod/ambassador/files/4536665/tab.txt)
