### ISSUE TITLE
Extension icon does not appear

### ISSUE THREAD

**Issue by Cixert** [Ascrod/ambassador#77]
It is the first time that I use Ambassador. I don't see any extension icon to start working with IRC. how does it work? I have tested on Firefox ESR 52.9.0 and on New Moon 28.9.0.a1. 
I have also tried Chatzilla with the same result.

**Comment by Ascrod** [comment]
By default, the option to launch Ambassador only appears on the Tools menu or the browser menu. The icon does not appear on any toolbar by default, but you can add it through the Customize menu.

Note that I can't guarantee that Ambassador will work 100% correctly on FF 52 or Fedor2's fork of Pale Moon, so you're on your own in that regard.

**Comment by Cixert** [comment]
Oh yeah. I see it in Firefox but I don't see it in the New Moon menu tools (Pale Moon fork)
I also don't see the option to enable an icon.

**Comment by Ascrod** [comment]
Icons are not "enabled". You have to go to the Customize menu and drag the icon you want out of it onto the desired toolbar.

**Comment by Cixert** [comment]
I don't know what it is or where the Customized menu is.

**Comment by Ascrod** [comment]
http://kb.mozillazine.org/Toolbar_customization_-_Firefox This is for Firefox, but it should also be relevant for every UXP-derived browser as well.

Regardless, this isn't an issue with Ambassador. The icon and menu show up where they are intended to on the applications that the Ambassador extension officially supports - Pale Moon, Basilisk, and Interlink.
