### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by PropercodeUK** [Ascrod/ambassador#83]
Other than to create malicious botnet controlled remotely, why would the IRC client require elevated Administrator privileges during Windows 10 installation from https://github.com/Ascrod/ambassador/releases/download/v1.3.0/ambassador-1.3.0.win64.installer.exe please and thank you?

**Comment by Ascrod** [comment]
Installing programs to C:\Program Files on Windows requires admin privileges. Files that reside in Program Files are better protected from malware running under non-admin credentials. This is common practice with software installation on Windows and many other platforms.

**Comment by PropercodeUK** [comment]
Creating a security hole in order to plug a perceived future vulnerability is not a wise choice. It is common practice to install userspace applications in userspace.

**Comment by Ascrod** [comment]
I'm not sure where you get your information, but I reiterate that requiring admin rights to install programs on Windows via installer is common practice. During the installation process, if you wish, you can change the install location to AppData or any other location that does not require admin rights, but without admin rights the installer cannot update the registry with important information like protocol association, which tells Windows that the program can handle irc protocol links.

If you do not trust or are unable to use the Windows installer for any reason, then you are free to download the 7z archive and run the program anywhere you like, and create shortcuts and the protocol association manually through Windows.
